name: 'Setup'
description: 'Checkout source code, and setup python and poetry'

runs:
  using: 'composite'
  steps:
    - name: 'Checkout source code'
      uses: 'actions/checkout@v4'
    - name: Install poetry
      shell: bash
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
          python-version: '3.11'    
          cache: 'poetry'
    - name: Check poetry.lock
      shell: bash
      run: poetry check --lock
